spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_banking
    username: postgres
    password: pgsql
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
server:
  port: 8082